
security:
  user:
    name: user
    password: 123456

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://user:123456@127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}


#Since Spring Boot 1.5.x all endpoints are secured by default. For the sake of brevity we’re disabling the security for now.
#Have a look at the security section on how to deal with secured endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"  #exposure all endpoints 暴露所有的端点
  endpoint:
    health:
      show-details: ALWAYS #show all health details health端点显示全部细节
  security:
    enabled: false
