eureka:
  client:
    service-url:
      defaultZone: http://drugstore:10.24@10.80.0.129:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  security:
    enabled: false
